[package]
name = "ekiden-runtime-loader"
version = "0.3.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
edition = "2018"

[dependencies]
# TODO: Update to released versions when released.
aesm-client = { git = "https://github.com/fortanix/rust-sgx", rev = "ecf51e6b48c854242841f169edbfb14445fd59fb", features = ["sgxs"]}
enclave-runner = { git = "https://github.com/fortanix/rust-sgx", rev = "ecf51e6b48c854242841f169edbfb14445fd59fb" }
sgxs-loaders = { git = "https://github.com/fortanix/rust-sgx", rev = "ecf51e6b48c854242841f169edbfb14445fd59fb" }
clap = "2.29.1"
failure = "0.1.5"
tokio = "0.1.17"
tokio-uds = "0.2.5"
futures = "0.1.25"

[[bin]]
name = "ekiden-runtime-loader"
path ="bin/main.rs"
