[workspace]
members = [
    "runtime",
    "runtime-loader",
    "client",
    "keymanager-client",
    "keymanager-runtime",
    "tools",

    # Test runtimes.
    "tests/runtimes/simple-keyvalue",
    # Test clients.
    "tests/clients/simple-keyvalue",
    "tests/clients/simple-keyvalue-enc",
    "tests/clients/simple-keyvalue-ops",
    "tests/clients/test-long-term",
]

[patch.crates-io]
# TODO: Remove when merged upstream (briansmith/ring#738).
ring = { git = "https://github.com/akash-fortanix/ring", branch = "sgx-target" }
# TODO: Remove when merged upstream (rust-lang-deprecated/rustc-serialize#195).
rustc-serialize = { git = "https://github.com/jethrogb/rustc-serialize", branch = "portability" }

[profile.release]
panic = "abort"
