[workspace]
members = [
    "runtime",
    "runtime-loader",
    "client",
    "keymanager-client",
    "keymanager-api-common",
    "keymanager-lib",
    "tools",

    # Test runtimes.
    "tests/runtimes/simple-keyvalue",
    "tests/runtimes/simple-keymanager",
    "tests/runtimes/simple-keymanager-upgrade",

    # Test clients.
    "tests/clients/simple-keyvalue",
    "tests/clients/simple-keyvalue-enc",
    "tests/clients/simple-keyvalue-ops",
    "tests/clients/test-long-term",
]

[patch.crates-io]
# TODO: Remove when merged upstream (briansmith/ring#738).
ring = { git = "https://github.com/oasislabs/ring-sgx", branch = "sgx-target" }

[profile.release]
panic = "abort"
