[package]
name = "ekiden-consensus-dummy"
version = "0.1.0"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden dummy in-memory consensus backend"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.1.0" }
ekiden-consensus-base = { path = "../base", version = "0.1.0" }
ekiden-scheduler-base = { path = "../../scheduler/base", version = "0.1.0" }
ekiden-storage-base = { path = "../../storage/base", version = "0.1.0" }
log = "0.4"

[dev-dependencies]
ekiden-beacon-base = { path = "../../beacon/base", version = "0.1.0" }
ekiden-beacon-dummy = { path = "../../beacon/dummy", version = "0.1.0" }
ekiden-registry-base = { path = "../../registry/base", version = "0.1.0" }
ekiden-registry-dummy = { path = "../../registry/dummy", version = "0.1.0" }
ekiden-scheduler-dummy = { path = "../../scheduler/dummy", version = "0.1.0" }
ekiden-storage-dummy = { path = "../../storage/dummy", version = "0.1.0" }
serde = "1.0"
serde_cbor = "0.8.2"
