[package]
name = "ekiden-instrumentation"
version = "0.2.0-alpha"
authors = ["Ekiden Developers <ekiden-dev@googlegroups.com>"]
description = "A lightweight instrumentation facade for Rust"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
failure = "0.1"
