[package]
name = "oasis-core-runtime"
version = "0.3.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
edition = "2018"

[dependencies]
log = "0.3"
slog = "2.4.1"
slog-json = "2.3.0"
slog-scope = "4.1.1"
slog-stdlog = "3.0.4-pre"
serde = "1.0.71"
serde_derive = "1.0"
serde_cbor = "0.10.2"
serde_json = "1.0.39"
serde_bytes = "~0.10"
serde_repr = "0.1.5"
lazy_static = "1.3.0"
crossbeam = "0.7.1"
byteorder = "1.3.1"
failure = "0.1.5"
sgx-isa = { version = "0.3.0", features = ["sgxstd"] }
# TODO: Change version when merged upstream (briansmith/ring#738).
ring = "0.16.11"
webpki = "0.21.2"
untrusted = "0.7.0"
bincode = "1.0.0"
snow = { version = "0.6.2", default-features = false, features = ["ring-accelerated"] }
percent-encoding = "1.0.1"
pem-iterator = "0.2.0"
chrono = "0.4.6"
base64 = "0.10.1"
rustc-hex = "2.0.1"
rand = "0.7.3"
futures = "0.1.25"
tokio-current-thread = "0.1.5"
tokio-executor = "0.1.6"
io-context = "0.2.0"
x25519-dalek = "0.6.0"
ed25519-dalek = "1.0.0-pre.3"
deoxysii = { git = "https://github.com/oasislabs/deoxysii-rust" }
tiny-keccak = "1.4.2"
sp800-185 = "0.2.0"
zeroize = "0.6"
intrusive-collections = "0.7"

[dev-dependencies]
# For storage interoperability tests only.
grpcio = "0.4.6"
tempfile = "3.0.7"
