[package]
name = "token"
version = "0.2.0-alpha"
authors = ["Raymond Cheng <me@raymondcheng.net>"]
build = "build.rs"

[features]
default = []

[dependencies]
ekiden-core = { path = "../../core/common" }
ekiden-trusted = { path = "../../core/trusted" }
ekiden-storage-base = { path = "../../storage/base" }
protobuf = "~2.0"
token-api = { path = "./api" }

[build-dependencies]
ekiden-tools = { path = "../../tools" }
ekiden-edl = { path = "../../core/edl" }
