# Copied from pipeline.yml.
docker_plugin_default_config: &docker_plugin_default_config
  image: "oasislabs/testing:0.3.0"
  always_pull: true
  workdir: /workdir
  volumes:
    - /var/lib/buildkite-agent/.coveralls:/root/.coveralls
    - /var/lib/buildkite-agent/.codecov:/root/.codecov
    # Shared Rust incremental compile caches.
    - /var/tmp/cargo_ic/debug:/var/tmp/artifacts/debug/incremental
    - /var/tmp/cargo_ic/debug_sgx:/var/tmp/artifacts/x86_64-unknown-linux-sgx/debug/incremental
    # Shared Rust package checkouts directory.
    - /var/tmp/cargo_pkg/git:/root/.cargo/git
    - /var/tmp/cargo_pkg/registry:/root/.cargo/registry
    # Shared Rust SGX standard library artifacts cache.
    - /var/tmp/xargo_cache:/root/.xargo
    # Shared Go package checkouts directory.
    - /var/tmp/go_pkg:/root/go/pkg
    # Intel SGX Application Enclave Services Manager (AESM) daemon running on
    # the Buildkite host.
    - /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket
    - /var/tmp/longtests:/var/tmp/longtests
  environment:
    - "LC_ALL=C.UTF-8"
    - "LANG=C.UTF-8"
    - "CARGO_TARGET_DIR=/var/tmp/artifacts"
    - "CARGO_INSTALL_ROOT=/root/.cargo"
    - "GOPROXY=https://proxy.golang.org/"
    - "SLACK_WEBHOOK_URL"
  propagate-environment: true
  unconfined: true

docker_plugin: &docker_plugin
  oasislabs/docker#v3.0.1-oasis1:
    <<: *docker_plugin_default_config

steps:
  - label: Transaction source tests
    parallelism: 1
    # Tests are set to run 6 hours + some buffer time.
    timeout_in_minutes: 380
    command: .buildkite/scripts/daily_txsource.sh
    env:
      TEST_BASE_DIR: /var/tmp/longtests
    agents:
      buildkite_agent_size: large
      buildkite_agent_class: stable
    # NOTE: we actually don't want to retry, but this is the only way that we
    # can execute the notify step only if tests failed.
    retry:
      automatic:
        limit: 1
      manual:
        allowed: false
        reason: "Create a new build to retry"
    plugins:
      <<: *docker_plugin
