[package]
name = "ekiden-db-edl"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden database EDL"
keywords = ["ekiden"]
repository = "https://github.com/ekiden/ekiden"

[dependencies]
ekiden-tools = { path = "../../tools", version = "0.2.0-alpha" }
