[package]
name = "ekiden-registry-client"
version = "0.1.0-alpha.4"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden registry RPC clients"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.1.0-alpha.4" }
ekiden-registry-api = { path = "../api", version = "0.1.0-alpha.4" }
ekiden-registry-base = { path = "../base", version = "0.1.0-alpha.4" }
grpcio = "0.2.2"
