[package]
name = "ekiden-db-untrusted"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden database (untrusted part)"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[features]
sgx-simulation = []

[dependencies]
sgx_types = { git = "https://github.com/oasislabs/rust-sgx-sdk", tag = "v1.0.5-ekiden1" }
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-enclave-untrusted = { path = "../../enclave/untrusted", version = "0.2.0-alpha" }
ekiden-instrumentation = { path = "../../instrumentation", version = "0.2.0-alpha" }
ekiden-storage-base = { path = "../../storage/base", version = "0.2.0-alpha" }
log = "0.4"
rustracing = "0.2.0"
rustracing_jaeger = { git = "https://github.com/oasislabs/rustracing_jaeger.git", tag = "0.2.0-ekiden1" }

[build-dependencies]
ekiden-tools = { path = "../../tools", version = "0.2.0-alpha" }
