[package]
name = "ekiden-storage-client"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden storage interface traits"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
rustracing = "0.2.0"
grpcio = { version = "~0.4.2", features = ["openssl"] }
futures = "0.1"
protobuf = "~2.0"

ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-registry-base = { path = "../../registry/base", version = "0.2.0-alpha" }
ekiden-storage-base = { path = "../base", version = "0.2.0-alpha" }
ekiden-scheduler-base = { path = "../../scheduler/base", version = "0.2.0-alpha" }
ekiden-tracing = { path = "../../tracing", version = "0.2.0-alpha" }

[build-dependencies]
ekiden-tools = { path = "../../tools", version = "0.2.0-alpha" }
protoc-grpcio = "0.2.0"
