[package]
name = "ekiden-common"
version = "0.1.0-alpha.3"
authors = ["Ekiden Developers <ekiden-dev@googlegroups.com>"]
description = "Ekiden common functionality (available to both trusted and untrusted parts)"
keywords = ["ekiden"]
repository = "https://github.com/ekiden/ekiden"

[features]
default = []
profiling = []

[dependencies]
protobuf = "1.4.3"
byteorder = "1"
fixed-hash = { version = "0.2.1", default-features = false }
etcommon-rlp = "0.2.3"
rustc-hex = "1.0"
ring = { git = "https://github.com/ekiden/ring", default-features = false, features = [ "rsa_signing" ], branch = "0.12.1-ekiden" }
untrusted = "0.5.1"
bigint = { version = "4", features = ["std"] }
chrono = "0.4.2"

[target.'cfg(target_env = "sgx")'.dependencies]
futures-sgx = { git = "https://github.com/ekiden/futures-rs" }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
rand = "0.4.2"
futures = "0.1"
