[package]
name = "ekiden-instrumentation-prometheus"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Prometheus frontend for Ekiden instrumentation"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[features]
default = ["server", "push"]
server = ["hyper", "http", "futures"]
push = ["futures"]

[dependencies]
ekiden-instrumentation = { path = "..", version = "0.2.0-alpha" }
prometheus = { version = "~0.4.2", features = ["push"] }
hyper = { version = "~0.12", optional = true }
http = { version = "~0.1.6", optional = true }
futures = { version = "~0.1", optional = true }
ekiden-common = { path = "../../common", "version" = "0.2.0-alpha" }
clap = { version = "2.29.1" }
log = "0.4"
