linters-settings:
  gofmt:
    simplify: false
  govet:
    check-shadowing: true
  maligned:
    suggest-new: true
  goimports:
    # Put local imports after 3rd-party packages.
    local-prefixes: github.com/oasisprotocol/oasis-core


linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - goconst
    - gocyclo
    - gofumpt
    - goimports
    - golint
    - gas
    - typecheck
    - ineffassign
    - megacheck
    - structcheck
    - unconvert
    - varcheck
    - govet
    - maligned
    - misspell

run:
  skip-dirs:
    # golang-ci-lint requires that files compile for certain linters
    # to run, and Go plugins do not compile unless `-buildmode=plugin`
    # is set, which linters do not do.
    - oasis-test-runner/scenario/pluginsigner/example_signer_plugin
