linters-settings:
  gofmt:
    simplify: false
  govet:
    check-shadowing: true
  maligned:
    suggest-new: true

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - goconst
    - gocyclo
    - gofumpt
    - golint
    - gas
    - typecheck
    - ineffassign
    - megacheck
    - structcheck
    - unconvert
    - varcheck
    - govet
    - maligned
