[package]
name = "ekiden-roothash-client"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden root hash RPC client"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-di = { path = "../../di", version = "0.2.0-alpha" }
ekiden-roothash-api = { path = "../api", version = "0.2.0-alpha" }
ekiden-roothash-base = { path = "../base", version = "0.2.0-alpha" }
grpcio = { version = "~0.4.2", features = ["openssl"] }
serde = "1.0.71"
serde_cbor = { git = "https://github.com/oasislabs/cbor", tag = "v0.9.0-ekiden1" }
serde_derive = "1.0"
