[package]
name = "ekiden-common-api"
version = "0.2.0-alpha"
authors = ["Ekiden Developers <ekiden-dev@googlegroups.com>"]
description = "Ekiden common API"
keywords = ["ekiden"]
repository = "https://github.com/ekiden/ekiden"
build = "build.rs"

[dependencies]
protobuf = "~2.0"

[target.'cfg(not(target_env = "sgx"))'.dependencies]
grpcio = { git = "https://github.com/ekiden/grpc-rs", tag = "v0.3.0-ekiden1", features = ["openssl"] }
futures = "0.1"

[build-dependencies]
ekiden-tools = { path = "../../tools", version = "0.2.0-alpha" }

[target.'cfg(not(target_env = "sgx"))'.build-dependencies]
protoc-grpcio = "0.2.0"
