[package]
name = "ekiden-common-api"
version = "0.1.0-alpha.4"
authors = ["Ekiden Developers <ekiden-dev@googlegroups.com>"]
description = "Ekiden common API"
keywords = ["ekiden"]
repository = "https://github.com/ekiden/ekiden"
build = "build.rs"

[dependencies]
protobuf = "~1.4"

[target.'cfg(not(target_env = "sgx"))'.dependencies]
grpcio = "0.2.2"
futures = "0.1"

[build-dependencies]
ekiden-tools = { path = "../../tools", version = "0.1.0-alpha.4" }

[target.'cfg(not(target_env = "sgx"))'.build-dependencies]
protoc-grpcio = "0.1.0"
