[package]
name = "ekiden-runtime-trusted"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden runtime interface (trusted part)"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-runtime-common = { path = "../common", version = "0.2.0-alpha" }
ekiden-enclave-trusted = { path = "../../enclave/trusted", version = "0.2.0-alpha" }
ekiden-roothash-base = { path = "../../roothash/base", version = "0.2.0-alpha" }
lazy_static = { version = "1.1.0", features = ["spin_no_std"] }
serde = "1.0.71"
serde_cbor = { git = "https://github.com/oasislabs/cbor", tag = "v0.9.0-ekiden1" }

[dev-dependencies]
serde_derive = "1.0"
