[package]
name = "ekiden-contract-edl"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden contract EDL"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
ekiden-tools = { path = "../../tools", version = "0.2.0-alpha" }
