name: Continuous integration

on: push

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v1
      - name: Install prerequisites
        run: |
          python -m pip install https://github.com/oasislabs/towncrier/archive/oasis-master.tar.gz
      - name: Check for presence of a Change Log fragment (only pull requests)
        run: |
          # Fetch the pull request' base branch so towncrier will be able to
          # compare the current branch with the base branch.
          # Source: https://github.com/actions/checkout/#fetch-all-branches.
          git fetch --no-tags --prune --depth=1 origin +refs/heads/${BASE_BRANCH}:refs/remotes/origin/${BASE_BRANCH}
          towncrier check --compare-with origin/${BASE_BRANCH}
        env:
          BASE_BRANCH: ${{ github.base_ref }}
        if: github.event_name == 'pull_request'
